### ISSUE TITLE
Connection to HomeAssistant-AddOn not possible

### ISSUE THREAD

**Issue by PottiMc** [satheshshiva/Adguard-Home-Browser-Ext#3]
When I try to connect to my AdGuard HomeAssistant AddOn I get the error message "Failed to fetch". 

![image](https://github.com/satheshshiva/Adguard-Home-Browser-Ext/assets/39881308/3463af79-58b6-4278-85a4-c96f0703814a)

The IP adress is the one displayed in AdGuard. All devices in the network can access it as a DNS server.

![image](https://github.com/satheshshiva/Adguard-Home-Browser-Ext/assets/39881308/5466f423-b611-427f-88ef-003fb8925673)

Username and password is the Home Assistant login data as mentioned here [https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/DOCS.md](url).

Am I doing something wrong?

**Comment by PottiMc** [comment]
Sorry, I got it up and running now. The problem was, the HomeAssistant Addon is not enabling the port for the web interface in default. You got to check the mark on "Show not used ports" and enter a port in the settings. After that the extension can connect.

![image](https://github.com/satheshshiva/Adguard-Home-Browser-Ext/assets/39881308/e9fcc93d-3b32-4fbd-8bcb-af0cf0fe592d)

**Comment by satheshshiva** [comment]
@PottiMc Thanks for sharing.
