### ISSUE TITLE
Adguard Home in Home Assistant

### ISSUE THREAD

**Issue by DreadN** [satheshshiva/Adguard-Home-Browser-Ext#5]
I'm trying to put the ingress portal of Adguard Home add-on of Home Assistant but it does not work.
Is this a feasible scenario?

![image](https://github.com/user-attachments/assets/57fd2fa2-c4c3-4e54-bc5a-124815f8616b)

**Comment by satheshshiva** [comment]
You should be giving the just the server name. example: `http://adguard/` and not `http://adguard/<something>`

**Comment by satheshshiva** [comment]
No, I have not tested this with Home Assistant

**Comment by DreadN** [comment]
Ok thanks, that's probably why I can't connect via URI/user/password.
